import { SignalType } from "./ast";

/**
 * Represents a circuit artifact generated by the `CircuitArtifactGenerator`.
 *
 * @property {string} _format - The format version of the circuit artifact.
 * @property {string} circuitName - The name of the main component in the circuit.
 * @property {string} sourceName - The circuit file path relative to the project root.
 * @property {string} compilerVersion - The version of the Circom compiler specified in the circuit.
 * @property {Signal[]} signals - An array of `input` and `output` signals used in the circuit.
 */
export interface CircuitArtifact {
  _format: string;
  circuitName: string;
  sourceName: string;
  compilerVersion: string;
  signals: Signal[];
}

/**
 * Represents a signal used in a circuit.
 *
 * @property {string} name - The name of the signal.
 * @property {SignalType} type - The type of the signal (currently supported: "input", "output").
 * @property {string} internalType - The internal type of the signal (currently supported: "bigint").
 */
export interface Signal {
  name: string;
  type: SignalType;
  internalType: string;
}
